
h = c("/well/ukbiobank/expt/V2_QCed.SNP-QC/src/V2_QCed.snpqc-tests.R","/well/ukbiobank/expt/V2_QCed.SNP-QC/src/V2_QCed.bin2clusterplots.R","/well/ukbiobank/qcoutput.V2_QCed.sample-QC/QC-Scripts/R/scripts/readPSperformance.R","/well/ukbiobank/qcoutput.V2_QCed.sample-QC/QC-Scripts/R/scripts/auxFunctions.R")
for(s in h) source(s)
source("/well/ukbiobank/qcoutput.V2_QCed.sample-QC/QC-Scripts/R/scripts/ukbbcolors.R")

source("/well/ukbiobank/qcoutput.V2_QCed.sample-QC/QC-Scripts/R/scripts/compute-Moran.R")

library(igraph)
library(xtable)
library(hexbin)
library(latticeExtra)
library(viridis)


setwd('/well/ukbiobank/qcoutput.V2_QCed.sample-QC/QC-Scripts/forPaper')


# Main sample QC file for release (generated by $basedir/QC-Scripts/Sample-QC/Flags/create-sample-table.R)
###########
releaseSampleQCPrefix = 'b1__b11-b001__b095-sampleTable_v4'
###########


load(paste0('../../data/ForRelease/',releaseSampleQCPrefix,'_allColumns.RData'),verbose=TRUE)
#PCsAll = PCs

#### LOAD IN THE WB PCs. Created by plot-White-British-PCA.R
load(file=paste0(baseSampleQCDir,"/data/PCA/b1__b11-b001__b095-pca-UKbio-White_British_subset.RData") ,verbose=TRUE)


PCs = PCs[PCs$PIID%in%outTable$PIID,]
dim(PCs)
outTable2 = outTable[match(PCs$PIID,outTable$PIID),]
dim(outTable2)

nPCs = sum(grepl("PC",colnames(PCs)))
print(paste0(nPCs," PCs"))

## Plot the first XX PCs by country of birth
cob =  get.place.of.birth(outTable2)
eth = ethnicity2pop(outTable2$Ethnic.background)
tab= table(cob)
cob2 = cob
minSamples=100
tooSmall = names(tab[tab<minSamples])
paste0(sum(cob%in%tooSmall)," inds in groups smaller than ",minSamples)
cob2[cob%in%c(tooSmall,"Prefer_not_to_answer","Do_not_know")] = "Other/Unknown"


###############
args <- commandArgs(trailingOnly= TRUE)
print(args)
###############
###############
myPC = args[1]
cellSize = as.numeric(args[2])
nreps = as.numeric(args[3])
kNeighbours = as.numeric(args[4])
###############




########################
# This section is the same as what is in plot-White_British-PCA_v2.R

# get mapping shape files etc.
load(mapFileUK0,verbose=TRUE)
uk0 = british_isles_sp_map_bng
uk0@bbox = rbind(c(-210500,665695),c(-10000,1235640))
# original coordinates
#          min       max
#x -296677.815  655695.6
#y    5408.466 1295640.3

baseMap = spplot(uk0,zcol="ID_0",col.regions="transparent",colorkey=FALSE,main="hello")

png("plots/test.png",height=1500,width=1000,res=150)
print(baseMap)
dev.off()

country.centres <- t(sapply(uk0@polygons,FUN=slot,name="labpt"))
colnames(country.centres) <- c("X","Y")
rownames(country.centres) <- uk0@data[,"ISO"]

###############
# Get BNG coordinates
x = outTable2$Place.of.birth.in.UK...east.co.ordinate
y = outTable2$Place.of.birth.in.UK...north.co.ordinate

# anyone with -1 is missing.
x[x==-1] = NA
y[y==-1] = NA

 # anyone in the sea is a bit dodgy .Turns out they're all from the pilot assessment centre. (see below)
# 281 individuals apparently in the sea. They were all in the stockport_pilot.
inTheSea = which((x<80000)&(y<(90000)))
x[inTheSea] = NA
y[inTheSea] = NA

sum((!is.na(x))&(!is.na(y)))
# 394603 samples!

###############
# Randomly geocode people born in Northern Ireland, and the Republic of Ireland.
NorthernIreland = which(cob2=="Northern_Ireland")

# Find northern Ireland polygon in GBR set
# NI = which(sapply(myMap@polygons[[1]]@Polygons,function(i) gContains(SpatialPolygons(Srl = list(Polygons(list(i),ID=1)),proj4string = CRS(proj4string(myMap))),
#                                                          SpatialPoints(coords = cbind(#98518,542448),proj4string = CRS(proj4string(myMap))))))
NIpolyRaw = uk0@polygons[[1]]@Polygons[214][[1]]
NIpoly = SpatialPolygons(list(Polygons(list(NIpolyRaw),ID="NI")),proj4string=CRS(proj4string(uk0)))
bb = bbox(NIpoly)
jitx=runif(5000,bb[1,1],bb[1,2])
jity=runif(5000,bb[2,1],bb[2,2])
pts=SpatialPoints(coords=cbind(jitx,jity),proj4string=CRS(proj4string((uk0))))
test=sp::over(pts,NIpoly)
good=which(!is.na(test))

length(good)>length(NorthernIreland)

# set their coordinates
x[NorthernIreland] = pts@coords[good[1:length(NorthernIreland)],1]
y[NorthernIreland] = pts@coords[good[1:length(NorthernIreland)],2]

sum((!is.na(x))&(!is.na(y)))

###############
# Randomly geocode people born in Northern Ireland, and the Republic of Ireland.
RepubIreland = which(cob2=="Republic_of_Ireland")

# Find northern Ireland polygon in GBR set
# NI = which(sapply(myMap@polygons[[1]]@Polygons,function(i) gContains(SpatialPolygons(Srl = list(Polygons(list(i),ID=1)),proj4string = CRS(proj4string(myMap))),
#                                                          SpatialPoints(coords = cbind(#98518,542448),proj4string = CRS(proj4string(myMap))))))
NIpoly2 = uk0[which(uk0@data[,"ISO"]=="IRL"),]
bb=bbox(NIpoly2)

bbPoly = SpatialPolygons(list(Polygons(list(Polygon(bb)),ID="bb")),proj4string=CRS(proj4string(uk0)))

    jitx=runif(5000,bb[1,1],bb[1,2])
    jity=runif(5000,bb[2,1],bb[2,2])
    pts=SpatialPoints(coords=cbind(jitx,jity),proj4string=CRS(proj4string((uk0))))
    test=sp::over(pts,NIpoly2)
    good=which(!is.na(test))

length(good)>length(NorthernIreland)

# set their coordinates
x[RepubIreland] = pts@coords[good[1:length(RepubIreland)],1]
y[RepubIreland] = pts@coords[good[1:length(RepubIreland)],2]

sum((!is.na(x))&(!is.na(y)))

notNA = (!is.na(x))&(!is.na(y))


colors = magma(10)
mapHeight = 0.93
mapViewPort = viewport(y=1,height=mapHeight,width=1,just="top")
histViewPort = viewport(y=0,height=(1-mapHeight),width=0.8,just="bottom")


# get spatial grid

coords = cbind(x,y)
notNA = (!is.na(rowSums(coords[,1:2]))) & (!is.na(PCs[["PC1"]]))
myExtent = rbind(range(coords[notNA,1]),range(coords[notNA,2]))


####################
# Load output from aggragation

load(file=paste0("PCA-POB-WhiteBritishSubset-GridStats-",cellSize/1000,"KmCells.RData"),verbose=TRUE)

#########
i=myPC
#########


##### Real stat
pc = paste0("PC",i)
print(pc)

values = PCs[[pc]]
Agg = get(paste0("Aggs.",cellSize/1000))[[pc]]

myWeightsMatrix = get(paste0("myWeightsMatrix",kNeighbours))
print(paste0("Using weights matrix with nearest ",kNeighbours," nearest neighbours."))

thisMoran = myMoran(myMap=uk0,values,coords,mySpatialGrid,agg=Agg,cellSize=cellSize,colors=magma(10),baseMap,weightsList=myWeightsMatrix)

assign(paste0("moranOut2.",cellSize/1000,".pc",i),thisMoran)



##### permutation

## k nearest neighbours --- Find null using a permutation test!
                                        #set.seed(7293858)

Notinthesea = which(!is.na(over(Agg,uk0)[,1]))
NotintheseaOrNA = intersect(Notinthesea,which(!is.na(Agg@data[,1])))
N = sum(notNA)

print(date())

perm = sapply(1:nreps,function(x){
                                        #print(x)
                                        # permute the values (each permutation run takes about 32seconds ==> 106 mins per PC if we do 200 repeats. Best parallelise this, or run over night.)
    if(x%%10==0) print(x)
    newAgg = gridMeans(coords[notNA,],values[notNA][sample(1:N,size=N,replace=FALSE)],mySpatialGrid)
    myValues = newAgg@data$values[NotintheseaOrNA]
    out = moran.test(myValues,myWeightsMatrix)
    return( c(out$statistic,out$estimate,out$p.value) )
})
print(date())

assign(paste0("moranOut2.null.",cellSize/1000,".pc",i),perm)


save(list=c(paste0("moranOut2.",cellSize/1000,".pc",i),paste0("moranOut2.null.",cellSize/1000,".pc",i),"i","pc"),
         file=paste0("PCA-POB-WhiteBritishSubset-MoranResults-",cellSize/1000,"KmCells-",kNeighbours,"Neighbours-pc",i,".RData"))

print("DONE!!")
